# unbind default
unbind C-b

# Set new prefix
set -g prefix C-a

# allow sending prefix to nested tmux
bind C-a send-prefix

bind-key x kill-pane

# vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

setw -g aggressive-resize on

# Pane borders
set -g pane-active-border-style fg=cyan

# Status bar colors
set -g status-style bg=default,fg=white
set -g status-left-style bg=default
set -g window-status-current-style bg=default,fg=white
