hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("kitty --class scratchpad", { workspace = "special:magic silent" })
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
end)
